steps:
- checkout: self
  submodules: recursive
- template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
  # parameters:
  #   RELEASE_NOTES_VARIANT: VersionDate-HashSubjectAuthor-NoMerges-Categorized
  #   RELEASE_NOTES_PATH: .release-notes.md
