steps:
- checkout: self
  submodules: recursive
- template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
  # parameters:
  #   RELEASE_NAME: My release name
  #   RELEASE_NOTES_PATH: /path/to/.release-notes.md
  #   # RELEASE_NOTES_CONTENT: |
  #   #   My
  #   #
  #   #   multi-line
  #   #   release
  #   #   notes
  #   RELEASE_DRAFT: false
  #   RELEASE_PRERELEASE: false
  #   RELEASE_ASSETS: |
  #     path/to/asset1.tar.gz
  #     path/to/asset2.gz
  #     path/to/asset3.zip
  #     path/to/assets/*.gz
  #     path/to/assets/*.zip
